name: Deploy Static Website to AWS S3

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::169024357038:role/GitHubActions-SaintBlitz-Deploy
          aws-region: eu-west-2

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://saintblittz \
            --exclude ".git/**" \
            --exclude ".github/**" \
            --delete